name: Terraform GCP

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/258083003066/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-deployer@project-990b8649-da36-4d4c-9d9.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      # ---- DAG DEPLOY (application) ----
      - name: Sync Airflow DAGs to GCS
        run: |
          gsutil rsync -d -r dags/ gs://airflow-dags-258083003066/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug working directory
        run: |
          pwd
          ls -la
          find . -name backend.tf


      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -reconfigure

      - name: Debug state
        working-directory: terraform/envs/dev
        run: terraform state list || true

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve
