name: Terraform GCP

on:
  pull_request:
    paths:
      - terraform/**
      - modules/**
      - envs/**
      - scripts/startup/**
      - .github/workflows/terraform.yml

  push:
    branches: [ "main" ]
    paths:
      - terraform/**
      - modules/**
      - envs/**
      - scripts/startup/**
      - .github/workflows/terraform.yml

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/258083003066/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-deployer@project-990b8649-da36-4d4c-9d9.iam.gserviceaccount.com"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -reconfigure

      - name: Terraform Plan
        id: plan
        working-directory: terraform/envs/dev
        run: |
          terraform plan -out=tfplan
          terraform show -json tfplan > plan.json

      - name: Summarize plan
        if: github.event_name == 'pull_request'
        id: summary
        working-directory: terraform/envs/dev
        run: |
          ADDS=$(jq '[.resource_changes[] | select(.change.actions | index("create"))] | length' plan.json)
          CHANGES=$(jq '[.resource_changes[] | select(.change.actions | index("update"))] | length' plan.json)
          DESTROYS=$(jq '[.resource_changes[] | select(.change.actions | index("delete"))] | length' plan.json)

          cat <<EOF > summary.md
          ### Terraform Plan Summary

          | Action   | Count |
          |---------:|------:|
          | ➕ Create | $ADDS |
          | ✏️ Update | $CHANGES |
          | ❌ Delete | $DESTROYS |

          \`\`\`
          terraform/envs/dev
          \`\`\`
          EOF

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('terraform/envs/dev/summary.md', 'utf8');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });


      - name: Detect plan changes
        id: diff
        working-directory: terraform/envs/dev
        run: |
          if jq -e '.resource_changes | length == 0' plan.json; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
            echo "No infrastructure changes detected."
          else
            echo "changes=true" >> "$GITHUB_OUTPUT"
            echo "Infrastructure changes detected."
          fi

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && steps.diff.outputs.changes == 'true'
        working-directory: terraform/envs/dev
        run: terraform apply -auto-approve tfplan
